### ISSUE TITLE
KafkaConsumer NullPointerException on absent key

### ISSUE THREAD

**Issue by arbitrary-dev** [fd4s/fs2-kafka#593]
Please allow consuming records without key supplied, otherwise:
```
[info] java.lang.NullPointerException: null
[info] 	at java.base/java.lang.String.<init>(String.java:561)
[info] 	at fs2.kafka.Deserializer$.$anonfun$string$1(Deserializer.scala:208)
[info] 	at fs2.kafka.Deserializer$.$anonfun$lift$1(Deserializer.scala:184)
[info] 	at fs2.kafka.Deserializer$$anon$1.deserialize(Deserializer.scala:133)
[info] 	at fs2.kafka.ConsumerRecord$.deserializeFromBytes(ConsumerRecord.scala:173)
[info] 	at fs2.kafka.ConsumerRecord$.fromJava(ConsumerRecord.scala:184)
[info] 	at fs2.kafka.internal.KafkaConsumerActor.$anonfun$records$2(KafkaConsumerActor.scala:410)
[info] 	at cats.data.NonEmptyVectorInstances$$anon$1.traverse(NonEmptyVector.scala:416)
[info] 	at cats.data.NonEmptyVectorInstances$$anon$1.traverse(NonEmptyVector.scala:363)
[info] 	at cats.Traverse$Ops.traverse(Traverse.scala:181)
[info] 	at cats.Traverse$Ops.traverse$(Traverse.scala:180)
[info] 	at cats.Traverse$ToTraverseOps$$anon$3.traverse(Traverse.scala:206)
[info] 	at fs2.kafka.internal.KafkaConsumerActor.$anonfun$records$1(KafkaConsumerActor.scala:408)
[info] 	at cats.data.Chain$.$anonfun$traverseViaChain$1(Chain.scala:791)
[info] 	at cats.Later.value$lzycompute(Eval.scala:148)
[info] 	at cats.Later.value(Eval.scala:147)
[info] 	at cats.Eval$.loop$1(Eval.scala:338)
[info] 	at cats.Eval$.cats$Eval$$evaluate(Eval.scala:363)
[info] 	at cats.Eval$FlatMap.value(Eval.scala:284)
[info] 	at cats.data.Chain$.traverseViaChain(Chain.scala:819)
[info] 	at cats.instances.VectorInstances$$anon$1.traverse(vector.scala:96)
[info] 	at cats.instances.VectorInstances$$anon$1.traverse(vector.scala:15)
[info] 	at cats.Traverse$Ops.traverse(Traverse.scala:181)
[info] 	at cats.Traverse$Ops.traverse$(Traverse.scala:180)
[info] 	at cats.Traverse$ToTraverseOps$$anon$3.traverse(Traverse.scala:206)
[info] 	at fs2.kafka.internal.KafkaConsumerActor.records(KafkaConsumerActor.scala:405)
```

## Deps

Scala 2.13
fs2-kafka 1.4.0

**Comment by vlovgr** [comment]
If you change from `String` keys to `Option[String]` keys, it will treat `null` keys as `None`.
It is documented here: https://fd4s.github.io/fs2-kafka/docs/consumers#deserializers
