### ISSUE TITLE
A NPE is thrown from AvroDeserializer if the value is empty

### ISSUE THREAD

**Issue by channingwalton** [fd4s/fs2-kafka#992]
If a message contains no key / value then a NPE is thrown from AvroDeserializer. 
```
java.lang.NullPointerException: null
	at java.base/java.nio.ByteBuffer.wrap(ByteBuffer.java:422)
	at fs2.kafka.vulcan.AvroDeserializer$.$anonfun$using$4(AvroDeserializer.scala:30)
	at defer @ fs2.kafka.vulcan.AvroDeserializer$.$anonfun$using$3(AvroDeserializer.scala:28)
	at get @ fs2.internal.InterruptContext.$anonfun$eval$1(InterruptContext.scala:91)
	at mapN @ fs2.concurrent.Channel$.bounded(Channel.scala:144)
	at map @ fs2.kafka.ConsumerRecord$.fromJava(ConsumerRecord.scala:184)
	at map @ fs2.kafka.internal.KafkaConsumerActor.$anonfun$records$2(KafkaConsumerActor.scala:406)
	at defer @ fs2.kafka.vulcan.AvroDeserializer$.$anonfun$using$3(AvroDeserializer.scala:28)
	at get @ fs2.internal.InterruptContext.$anonfun$eval$1(InterruptContext.scala:91)
	at defer @ fs2.kafka.vulcan.AvroDeserializer$.$anonfun$using$3(AvroDeserializer.scala:28)
	at get @ fs2.internal.InterruptContext.$anonfun$eval$1(InterruptContext.scala:91)
	at mapN @ fs2.concurrent.Channel$.bounded(Channel.scala:144)
	at map @ fs2.kafka.ConsumerRecord$.fromJava(ConsumerRecord.scala:184)
	at map @ fs2.kafka.internal.KafkaConsumerActor.$anonfun$records$2(KafkaConsumerActor.scala:406)
	at traverse @ fs2.kafka.KafkaConsumer$$anon$1.$anonfun$partitionsMapStream$23(KafkaConsumer.scala:259
```

[PR](https://github.com/fd4s/fs2-kafka/pull/993)

**Comment by channingwalton** [comment]
I think that the byte array [here](https://github.com/fd4s/fs2-kafka/blob/85db114efdb56fa8302a71b68ae2a6be56be57e9/modules/vulcan/src/main/scala/fs2/kafka/vulcan/AvroDeserializer.scala#L27) is null.

**Comment by OneCricketeer** [comment]
This introduced another bug that tombstone records can no longer be consumed.

You should pass through null, rather than throw an exception. Ref. https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java#L178

Also, why not just defer to / wrap KafkaAvroDeserializer class deserialize instead?

**Comment by mzuehlke** [comment]
Just came across the problem of handling tombstone. 
@OneCricketeer  did you found a workaround for this ?

**Comment by OneCricketeer** [comment]
@mzuehlke I use Confluent's deserializer, not fs2
